apiVersion: v1
kind: Service
metadata:
  name: postgres-dev-svc
  labels:
    name: postgres-dev-svc
    env: development
    app: product-api 
spec:
  selector:
    name: postgres-dev-pod
    type: dev-database
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
    
