apiVersion: v1
kind: Pod
metadata:
  name: postgres-dev-pod
  labels:
    name: postgres-dev-pod 
    env: development
    type: dev-database
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USERNAME
          value: postgres 
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
